2022-08-04T14:41:25.334854+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-08-04T14:41:25.334855+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2022-08-04T14:41:25.334855+00:00 app[web.1]: mod = importlib.import_module(module)
2022-08-04T14:41:25.334855+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2022-08-04T14:41:25.334856+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-08-04T14:41:25.334856+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-08-04T14:41:25.334857+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-08-04T14:41:25.334857+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2022-08-04T14:41:25.334857+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2022-08-04T14:41:25.334858+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2022-08-04T14:41:25.334858+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-08-04T14:41:25.334858+00:00 app[web.1]: File "/app/todolist_project/wsgi.py", line 16, in <module>
2022-08-04T14:41:25.334858+00:00 app[web.1]: application = get_wsgi_application()
2022-08-04T14:41:25.334859+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2022-08-04T14:41:25.334859+00:00 app[web.1]: django.setup(set_prefix=False)
2022-08-04T14:41:25.334871+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
2022-08-04T14:41:25.334871+00:00 app[web.1]: configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2022-08-04T14:41:25.334871+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
2022-08-04T14:41:25.334872+00:00 app[web.1]: self._setup(name)
2022-08-04T14:41:25.334872+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
2022-08-04T14:41:25.334872+00:00 app[web.1]: self._wrapped = Settings(settings_module)
2022-08-04T14:41:25.334873+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 222, in __init__
2022-08-04T14:41:25.334873+00:00 app[web.1]: raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
2022-08-04T14:41:25.334873+00:00 app[web.1]: ValueError: Incorrect timezone setting: Asia/taipei
2022-08-04T14:41:25.334879+00:00 app[web.1]: [2022-08-04 14:41:25 +0000] [9] [ERROR] Exception in worker process
2022-08-04T14:41:25.334879+00:00 app[web.1]: Traceback (most recent call last):
2022-08-04T14:41:25.334880+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2022-08-04T14:41:25.334880+00:00 app[web.1]: worker.init_process()
2022-08-04T14:41:25.334880+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
2022-08-04T14:41:25.334880+00:00 app[web.1]: self.load_wsgi()
2022-08-04T14:41:25.334881+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2022-08-04T14:41:25.334881+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-08-04T14:41:25.334881+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-08-04T14:41:25.334882+00:00 app[web.1]: self.callable = self.load()
2022-08-04T14:41:25.334882+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2022-08-04T14:41:25.334882+00:00 app[web.1]: return self.load_wsgiapp()
2022-08-04T14:41:25.334883+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2022-08-04T14:41:25.334883+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-08-04T14:41:25.334883+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
2022-08-04T14:41:25.334884+00:00 app[web.1]: mod = importlib.import_module(module)
2022-08-04T14:41:25.334884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2022-08-04T14:41:25.334884+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-08-04T14:41:25.334885+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2022-08-04T14:41:25.334885+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2022-08-04T14:41:25.334885+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2022-08-04T14:41:25.334885+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2022-08-04T14:41:25.334886+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2022-08-04T14:41:25.334886+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2022-08-04T14:41:25.334886+00:00 app[web.1]: File "/app/todolist_project/wsgi.py", line 16, in <module>
2022-08-04T14:41:25.334886+00:00 app[web.1]: application = get_wsgi_application()
2022-08-04T14:41:25.334887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2022-08-04T14:41:25.334887+00:00 app[web.1]: django.setup(set_prefix=False)
2022-08-04T14:41:25.334887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
2022-08-04T14:41:25.334888+00:00 app[web.1]: configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2022-08-04T14:41:25.334888+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
2022-08-04T14:41:25.334888+00:00 app[web.1]: self._setup(name)
2022-08-04T14:41:25.334889+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
2022-08-04T14:41:25.334889+00:00 app[web.1]: self._wrapped = Settings(settings_module)
2022-08-04T14:41:25.334889+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/django/conf/__init__.py", line 222, in __init__
2022-08-04T14:41:25.334889+00:00 app[web.1]: raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
2022-08-04T14:41:25.334890+00:00 app[web.1]: ValueError: Incorrect timezone setting: Asia/taipei
2022-08-04T14:41:25.335073+00:00 app[web.1]: [2022-08-04 14:41:25 +0000] [9] [INFO] Worker exiting (pid: 9)
2022-08-04T14:41:25.335131+00:00 app[web.1]: [2022-08-04 14:41:25 +0000] [10] [INFO] Worker exiting (pid: 10)
2022-08-04T14:41:25.429141+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=todolist-wayne.herokuapp.com request_id=3093146f-8162-44be-92d3-99dc4b50e64a fwd="61.63.117.220" dyno=web.1 connect=0ms service=148ms status=503 bytes=0 protocol=https
2022-08-04T14:41:25.431124+00:00 app[web.1]: Traceback (most recent call last):
2022-08-04T14:41:25.431150+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
2022-08-04T14:41:25.431457+00:00 app[web.1]: self.sleep()
2022-08-04T14:41:25.431458+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep
2022-08-04T14:41:25.431622+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2022-08-04T14:41:25.431631+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2022-08-04T14:41:25.431755+00:00 app[web.1]: self.reap_workers()
2022-08-04T14:41:25.431764+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2022-08-04T14:41:25.431934+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2022-08-04T14:41:25.432006+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-08-04T14:41:25.432019+00:00 app[web.1]: 
2022-08-04T14:41:25.432020+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2022-08-04T14:41:25.432020+00:00 app[web.1]: 
2022-08-04T14:41:25.432020+00:00 app[web.1]: Traceback (most recent call last):
2022-08-04T14:41:25.432022+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2022-08-04T14:41:25.432112+00:00 app[web.1]: sys.exit(run())
2022-08-04T14:41:25.432123+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2022-08-04T14:41:25.432218+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2022-08-04T14:41:25.432228+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
2022-08-04T14:41:25.432355+00:00 app[web.1]: super().run()
2022-08-04T14:41:25.432364+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
2022-08-04T14:41:25.432456+00:00 app[web.1]: Arbiter(self).run()
2022-08-04T14:41:25.432464+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
2022-08-04T14:41:25.432579+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2022-08-04T14:41:25.432588+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
2022-08-04T14:41:25.432741+00:00 app[web.1]: self.stop()
2022-08-04T14:41:25.432750+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
2022-08-04T14:41:25.432904+00:00 app[web.1]: time.sleep(0.1)
2022-08-04T14:41:25.432912+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2022-08-04T14:41:25.433032+00:00 app[web.1]: self.reap_workers()
2022-08-04T14:41:25.433041+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2022-08-04T14:41:25.433239+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2022-08-04T14:41:25.433372+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2022-08-04T14:41:25.592782+00:00 heroku[web.1]: Process exited with status 1
2022-08-04T14:41:25.836381+00:00 heroku[web.1]: State changed from up to crashed
2022-08-04T14:41:30.906559+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=todolist-wayne.herokuapp.com request_id=43ec4cef-6f3f-4234-aae9-1f3a0e35576e fwd="61.63.117.220" dyno=web.1 connect=5000ms service= status=503 bytes= protocol=https
